AWSTemplateFormatVersion: 2010-09-09
Description: GitHub OIDC for when GitHub wants to communicate with AWS.
Parameters:
  terraformBucketName:
    Type: String
    Description: Terraform state file bucket
Resources:
  # This is the bare-bones role.
  GitHubActionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHub_Actions_Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub 'arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com'
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringLike:
                ## THESE ARE CASE SENSITIVE!
                token.actions.githubusercontent.com:sub:
                  - repo:jeisonarenales/*:ref:refs/heads/main
              StringEqualsIgnoreCase:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
      Policies:
        - PolicyName: OidcSafetyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: OidcSafeties
                Effect: Deny
                Action:
                  - sts:AssumeRole
                Resource: '*'
        - PolicyName: TerraformStateFilePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Actions
                Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource:
                  - !Sub 'arn:aws:s3:::${terraformBucketName}'
                  - !Sub 'arn:aws:s3:::${terraformBucketName}/*'
              - Sid: AllowDeleteLockFile
                Effect: Allow
                Action:
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${terraformBucketName}/*.tflock'
              - Sid: ExplicitDenyDeleteStateBucketAndObjects
                Effect: Deny
                Action:
                  - s3:DeleteBucket
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                Resource:
                  - !Sub 'arn:aws:s3:::${terraformBucketName}'
                  - !Sub 'arn:aws:s3:::${terraformBucketName}/*.tfstate'

        - PolicyName: GitHubActionsDeployPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: AllowS3Actions
                Effect: Allow
                Action:
                  - s3:*
                Resource: '*'

  # This is the OIDC provider hookup itself. This tells AWS to delegate authN GitHub
  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 6938fd4d98bab03faadb97b34396831e3780aea1
      Url: https://token.actions.githubusercontent.com